/**
 * ISO currency definitions
 * 
 * This file contains a map of ISO currency codes to their metadata,
 * including name, symbol, and decimal places.
 */

/**
 * Interface for currency metadata
 */
export interface CurrencyMetadata {
  /** The ISO currency code (e.g., USD, EUR) */
  code: string;
  /** The currency name (e.g., US Dollar, Euro) */
  name: string;
  /** The currency symbol (e.g., $, €) */
  symbol: string;
  /** The number of decimal places for the currency */
  decimalPlaces: number;
}

/**
 * Map of ISO currency codes to their metadata
 */
export const ISO_CURRENCIES: Record<string, CurrencyMetadata> = {
  AED: { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'د.إ', decimalPlaces: 2 },
  AFN: { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', decimalPlaces: 2 },
  ALL: { code: 'ALL', name: 'Albanian Lek', symbol: 'L', decimalPlaces: 2 },
  AMD: { code: 'AMD', name: 'Armenian Dram', symbol: '֏', decimalPlaces: 2 },
  ANG: { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', decimalPlaces: 2 },
  AOA: { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', decimalPlaces: 2 },
  ARS: { code: 'ARS', name: 'Argentine Peso', symbol: '$', decimalPlaces: 2 },
  AUD: { code: 'AUD', name: 'Australian Dollar', symbol: '$', decimalPlaces: 2 },
  AWG: { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', decimalPlaces: 2 },
  AZN: { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', decimalPlaces: 2 },
  BAM: { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', decimalPlaces: 2 },
  BBD: { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', decimalPlaces: 2 },
  BDT: { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', decimalPlaces: 2 },
  BGN: { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', decimalPlaces: 2 },
  BHD: { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', decimalPlaces: 3 },
  BIF: { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', decimalPlaces: 0 },
  BMD: { code: 'BMD', name: 'Bermudan Dollar', symbol: '$', decimalPlaces: 2 },
  BND: { code: 'BND', name: 'Brunei Dollar', symbol: '$', decimalPlaces: 2 },
  BOB: { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', decimalPlaces: 2 },
  BRL: { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimalPlaces: 2 },
  BSD: { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', decimalPlaces: 2 },
  BTN: { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', decimalPlaces: 2 },
  BWP: { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', decimalPlaces: 2 },
  BYN: { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', decimalPlaces: 2 },
  BZD: { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', decimalPlaces: 2 },
  CAD: { code: 'CAD', name: 'Canadian Dollar', symbol: '$', decimalPlaces: 2 },
  CDF: { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', decimalPlaces: 2 },
  CHF: { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', decimalPlaces: 2 },
  CLP: { code: 'CLP', name: 'Chilean Peso', symbol: '$', decimalPlaces: 0 },
  CNY: { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', decimalPlaces: 2 },
  COP: { code: 'COP', name: 'Colombian Peso', symbol: '$', decimalPlaces: 2 },
  CRC: { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', decimalPlaces: 2 },
  CUP: { code: 'CUP', name: 'Cuban Peso', symbol: '₱', decimalPlaces: 2 },
  CVE: { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', decimalPlaces: 2 },
  CZK: { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', decimalPlaces: 2 },
  DJF: { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', decimalPlaces: 0 },
  DKK: { code: 'DKK', name: 'Danish Krone', symbol: 'kr', decimalPlaces: 2 },
  DOP: { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', decimalPlaces: 2 },
  DZD: { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', decimalPlaces: 2 },
  EGP: { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', decimalPlaces: 2 },
  ERN: { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', decimalPlaces: 2 },
  ETB: { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', decimalPlaces: 2 },
  EUR: { code: 'EUR', name: 'Euro', symbol: '€', decimalPlaces: 2 },
  FJD: { code: 'FJD', name: 'Fijian Dollar', symbol: '$', decimalPlaces: 2 },
  FKP: { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', decimalPlaces: 2 },
  GBP: { code: 'GBP', name: 'British Pound', symbol: '£', decimalPlaces: 2 },
  GEL: { code: 'GEL', name: 'Georgian Lari', symbol: '₾', decimalPlaces: 2 },
  GHS: { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', decimalPlaces: 2 },
  GIP: { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', decimalPlaces: 2 },
  GMD: { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', decimalPlaces: 2 },
  GNF: { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', decimalPlaces: 0 },
  GTQ: { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', decimalPlaces: 2 },
  GYD: { code: 'GYD', name: 'Guyanaese Dollar', symbol: '$', decimalPlaces: 2 },
  HKD: { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$', decimalPlaces: 2 },
  HNL: { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', decimalPlaces: 2 },
  HRK: { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', decimalPlaces: 2 },
  HTG: { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', decimalPlaces: 2 },
  HUF: { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', decimalPlaces: 2 },
  IDR: { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimalPlaces: 2 },
  ILS: { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', decimalPlaces: 2 },
  INR: { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimalPlaces: 2 },
  IQD: { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', decimalPlaces: 3 },
  IRR: { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', decimalPlaces: 2 },
  ISK: { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', decimalPlaces: 0 },
  JMD: { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', decimalPlaces: 2 },
  JOD: { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', decimalPlaces: 3 },
  JPY: { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimalPlaces: 0 },
  KES: { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', decimalPlaces: 2 },
  KGS: { code: 'KGS', name: 'Kyrgystani Som', symbol: 'с', decimalPlaces: 2 },
  KHR: { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', decimalPlaces: 2 },
  KMF: { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', decimalPlaces: 0 },
  KPW: { code: 'KPW', name: 'North Korean Won', symbol: '₩', decimalPlaces: 2 },
  KRW: { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimalPlaces: 0 },
  KWD: { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', decimalPlaces: 3 },
  KYD: { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', decimalPlaces: 2 },
  KZT: { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', decimalPlaces: 2 },
  LAK: { code: 'LAK', name: 'Laotian Kip', symbol: '₭', decimalPlaces: 2 },
  LBP: { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', decimalPlaces: 2 },
  LKR: { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', decimalPlaces: 2 },
  LRD: { code: 'LRD', name: 'Liberian Dollar', symbol: '$', decimalPlaces: 2 },
  LSL: { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', decimalPlaces: 2 },
  LYD: { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', decimalPlaces: 3 },
  MAD: { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', decimalPlaces: 2 },
  MDL: { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', decimalPlaces: 2 },
  MGA: { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', decimalPlaces: 2 },
  MKD: { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', decimalPlaces: 2 },
  MMK: { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', decimalPlaces: 2 },
  MNT: { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', decimalPlaces: 2 },
  MOP: { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', decimalPlaces: 2 },
  MRU: { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', decimalPlaces: 2 },
  MUR: { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', decimalPlaces: 2 },
  MVR: { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', decimalPlaces: 2 },
  MWK: { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', decimalPlaces: 2 },
  MXN: { code: 'MXN', name: 'Mexican Peso', symbol: '$', decimalPlaces: 2 },
  MYR: { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimalPlaces: 2 },
  MZN: { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', decimalPlaces: 2 },
  NAD: { code: 'NAD', name: 'Namibian Dollar', symbol: '$', decimalPlaces: 2 },
  NGN: { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', decimalPlaces: 2 },
  NIO: { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', decimalPlaces: 2 },
  NOK: { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', decimalPlaces: 2 },
  NPR: { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', decimalPlaces: 2 },
  NZD: { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', decimalPlaces: 2 },
  OMR: { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', decimalPlaces: 3 },
  PAB: { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', decimalPlaces: 2 },
  PEN: { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.', decimalPlaces: 2 },
  PGK: { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', decimalPlaces: 2 },
  PHP: { code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimalPlaces: 2 },
  PKR: { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', decimalPlaces: 2 },
  PLN: { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', decimalPlaces: 2 },
  PYG: { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', decimalPlaces: 0 },
  QAR: { code: 'QAR', name: 'Qatari Rial', symbol: 'ر.ق', decimalPlaces: 2 },
  RON: { code: 'RON', name: 'Romanian Leu', symbol: 'lei', decimalPlaces: 2 },
  RSD: { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', decimalPlaces: 2 },
  RUB: { code: 'RUB', name: 'Russian Ruble', symbol: '₽', decimalPlaces: 2 },
  RWF: { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', decimalPlaces: 0 },
  SAR: { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', decimalPlaces: 2 },
  SBD: { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', decimalPlaces: 2 },
  SCR: { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', decimalPlaces: 2 },
  SDG: { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', decimalPlaces: 2 },
  SEK: { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', decimalPlaces: 2 },
  SGD: { code: 'SGD', name: 'Singapore Dollar', symbol: '$', decimalPlaces: 2 },
  SHP: { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', decimalPlaces: 2 },
  SLL: { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', decimalPlaces: 2 },
  SOS: { code: 'SOS', name: 'Somali Shilling', symbol: 'S', decimalPlaces: 2 },
  SRD: { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', decimalPlaces: 2 },
  SSP: { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', decimalPlaces: 2 },
  STN: { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', decimalPlaces: 2 },
  SYP: { code: 'SYP', name: 'Syrian Pound', symbol: '£', decimalPlaces: 2 },
  SZL: { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', decimalPlaces: 2 },
  THB: { code: 'THB', name: 'Thai Baht', symbol: '฿', decimalPlaces: 2 },
  TJS: { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', decimalPlaces: 2 },
  TMT: { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', decimalPlaces: 2 },
  TND: { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', decimalPlaces: 3 },
  TOP: { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', decimalPlaces: 2 },
  TRY: { code: 'TRY', name: 'Turkish Lira', symbol: '₺', decimalPlaces: 2 },
  TTD: { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', decimalPlaces: 2 },
  TWD: { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', decimalPlaces: 2 },
  TZS: { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', decimalPlaces: 2 },
  UAH: { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', decimalPlaces: 2 },
  UGX: { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', decimalPlaces: 0 },
  USD: { code: 'USD', name: 'US Dollar', symbol: '$', decimalPlaces: 2 },
  UYU: { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', decimalPlaces: 2 },
  UZS: { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв', decimalPlaces: 2 },
  VES: { code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S', decimalPlaces: 2 },
  VND: { code: 'VND', name: 'Vietnamese Đồng', symbol: '₫', decimalPlaces: 0 },
  VUV: { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', decimalPlaces: 0 },
  WST: { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', decimalPlaces: 2 },
  XAF: { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', decimalPlaces: 0 },
  XCD: { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', decimalPlaces: 2 },
  XOF: { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', decimalPlaces: 0 },
  XPF: { code: 'XPF', name: 'CFP Franc', symbol: '₣', decimalPlaces: 0 },
  YER: { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', decimalPlaces: 2 },
  ZAR: { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimalPlaces: 2 },
  ZMW: { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', decimalPlaces: 2 },
  ZWL: { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$', decimalPlaces: 2 },
};